//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagamento()
        {
            this.Transacao = new HashSet<Transacao>();
            this.PagamentoParcela = new HashSet<PagamentoParcela>();
        }
    
        public int Sequencia { get; set; }
        public System.DateTime Data { get; set; }
        public double ValorTotal { get; set; }
        public double ValorEntrada { get; set; }
        public double ValorTroco { get; set; }
        public double ValorParcelamento { get; set; }
        public double ValorDesconto { get; set; }
        public double ValorAcrescimo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacao> Transacao { get; set; }
        public virtual Caixa Caixa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoParcela> PagamentoParcela { get; set; }
    }
}
