//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentoParcela
    {
        public int Sequencia { get; set; }
        public int Parcela { get; set; }
        public double Valor { get; set; }
        public TipoDocumentoFinan TipoDocumento { get; set; }
        public int NumeroDocumento { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public string Adicional { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
        public virtual HistoricoCaixa HistoricoCaixa { get; set; }
    }
}
