//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.TransacaoItem = new HashSet<TransacaoItem>();
            this.Promocao = new Promocao();
        }
    
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public string Especie { get; set; }
        public string CST { get; set; }
        public string NCM { get; set; }
        public double Aliquota { get; set; }
        public double ValorCusto { get; set; }
        public double ValorVenda { get; set; }
    
        public Promocao Promocao { get; set; }
    
        public virtual Referencia Referencia { get; set; }
        public virtual Tamanho Tamanho { get; set; }
        public virtual Variante Variante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransacaoItem> TransacaoItem { get; set; }
    }
}
