//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    
    public partial class Promocao
    {
        public int Codigo { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataTermino { get; set; }
        public double Valor { get; set; }
    }
}
