//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    
    public enum TipoModalidade : int
    {
        Venda = 1,
        DevoulcaoVenda = 2,
        Compra = 3,
        DevolucaoCompra = 4
    }
}
