//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    
    public enum TipoDocumentoFiscal : int
    {
        NaoFiscal = 0,
        NotaManual = 1,
        CupomFiscal = 71,
        NotaFiscalEletronica = 55,
        NotaFiscalConsumidorFiscal = 65,
        CupomFiscalEletronica = 59
    }
}
