//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    
    public enum TipoDocumentoFinan : int
    {
        Dinheiro = 1,
        Cheque = 2,
        CartaoDeCredito = 3,
        CartaoDeDebito = 4,
        CreditoLoja = 5,
        ValeAlimentacao = 10,
        ValeRefeicao = 11,
        ValePresente = 12,
        ValeCombustivel = 13,
        Outros = 99
    }
}
