//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoVenda.Dominio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransacaoItem
    {
        public int Sequencia { get; set; }
        public string CodigoItem { get; set; }
        public string DescricaoItem { get; set; }
        public string CST { get; set; }
        public string CSOSN { get; set; }
        public string CFOP { get; set; }
        public double Qtde { get; set; }
        public double Aliquota { get; set; }
        public double ValorCusto { get; set; }
        public double ValorUnitario { get; set; }
        public double ValorBruto { get; set; }
        public double ValorDesconto { get; set; }
        public double ValorAcrescimo { get; set; }
        public double ValorLiquido { get; set; }
    
        public virtual Transacao Transacao { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
